---
- name: Copy Jython Script File
  copy:
    src: files/was_app_deploy.jy
    dest: /tmp/was_app_deploy.jy
    force: true

- name:          "Deploy an Appliation"
  command:
    argv:
      - "{{ __was_install_location }}/profiles/{{ __dmgr_profile_name }}/bin/wsadmin.sh" 
      - -lang 
      - jython 
      - -conntype 
      - SOAP 
      - -host 
      - rhel2 
      - -username 
      - wasadmin 
      - -password 
      - changeit 
      - -f 
      - /tmp/was_app_deploy.jy 
      - "{{ __app_location }}"
      - "{{ __server_name }}"
      - "{{ __node_name }}"
      - "{{ __cell_name }}"
  register:      cout
  changed_when:  cout.rc == 0
  failed_when:   cout.rc != 0
  