---
- name:                    WAS ND - Create Profile
  hosts:                   dmgr,was_servers
  #  serial:                  2
  become:                  true
  roles:
    - roles/was-dmgr-create-profile